# This Jupyter doc goes through the basics of PyTorch tensor functionality

## Imports

In [1]:
import torch
import numpy as np

## The basic operations

In [2]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [3]:
a[4] *= 2

In [4]:
a

tensor([1., 1., 1., 1., 2.])

In [5]:
np.random.seed(42)
x = np.random.randint(0, 5, 10)
y = np.random.randint(0, 5, 10)
z = torch.tensor(list(zip(x,y)))
z

tensor([[3, 3],
        [4, 2],
        [2, 4],
        [4, 1],
        [4, 3],
        [1, 1],
        [2, 3],
        [2, 4],
        [2, 0],
        [4, 3]])

In [6]:
print(z.shape)
z[2,1]

torch.Size([10, 2])


tensor(4)

In [7]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])
batch_t = torch.randn(2, 3, 5, 5)
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [8]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
img_weights = img_t * unsqueezed_weights
batch_weights = batch_t * unsqueezed_weights
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
unsqueezed_weights.shape

torch.Size([3, 1, 1])

## Naming indices

In [9]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
img_named

/home/matthew/anaconda3/lib/python3.8/site-packages/torch/tensor.py:775: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370117127/work/c10/core/TensorImpl.h:848.)
  return super(Tensor, self).refine_names(names)


tensor([[[-0.5480, -0.0092, -0.1346, -0.1241, -2.2838],
         [ 1.1230,  0.5971, -0.4346, -0.3042,  0.1206],
         [ 0.1667, -1.8539, -1.1092, -0.5838,  0.0361],
         [ 1.3178,  1.3445, -1.0983, -1.0922,  0.5796],
         [-0.8890,  2.0867,  0.4058, -0.1027, -2.0018]],

        [[ 0.9609,  0.7659,  1.3246, -1.3996,  0.1082],
         [-0.7594,  0.2788,  0.9425, -0.6120,  0.9174],
         [ 1.9461,  0.3276, -0.1381, -2.6240, -0.1631],
         [ 1.7288,  0.1805, -1.1185,  2.1546, -0.9104],
         [-1.6101, -1.7304,  0.8133,  0.3978,  0.2337]],

        [[ 1.4215, -0.1214,  0.5355,  2.0839, -0.2917],
         [ 0.1251, -1.1606, -0.0918, -0.3545, -0.7282],
         [-1.3327,  0.2494, -1.2413, -1.5679, -1.5581],
         [ 0.6422,  0.2674,  1.5547,  0.1086,  0.8400],
         [ 0.6756,  0.3440,  1.4134,  1.1330,  0.6265]]],
       names=('channels', 'rows', 'columns'))

## The contiguous storage of the tensor in memory (always 1-d)

In [10]:
img_named.storage()

 -0.5479626655578613
 -0.009231677278876305
 -0.13463722169399261
 -0.1241041049361229
 -2.2837562561035156
 1.1229878664016724
 0.5970594882965088
 -0.4346407651901245
 -0.3041590750217438
 0.12058303505182266
 0.1666673868894577
 -1.8538708686828613
 -1.1092164516448975
 -0.5837698578834534
 0.036127254366874695
 1.3178149461746216
 1.3444547653198242
 -1.0982705354690552
 -1.0921915769577026
 0.5795955061912537
 -0.8890042304992676
 2.086700201034546
 0.405773788690567
 -0.10267657041549683
 -2.0018293857574463
 0.9609050750732422
 0.7659482359886169
 1.32461678981781
 -1.3996225595474243
 0.10822612792253494
 -0.7593819499015808
 0.2788005769252777
 0.9424800872802734
 -0.6119564771652222
 0.9173759818077087
 1.9460675716400146
 0.327575147151947
 -0.13810975849628448
 -2.6240336894989014
 -0.16309617459774017
 1.728796362876892
 0.18045714497566223
 -1.118470549583435
 2.154550790786743
 -0.9104261994361877
 -1.6100770235061646
 -1.730409860610962
 0.8132521510124207
 0.3978330194

## Tensor methods with the form *_() modify data inplace

In [11]:
img_named.zero_()
img_named

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], names=('channels', 'rows', 'columns'))

## Transposing without copying to new memory

In [12]:
z

tensor([[3, 3],
        [4, 2],
        [2, 4],
        [4, 1],
        [4, 3],
        [1, 1],
        [2, 3],
        [2, 4],
        [2, 0],
        [4, 3]])

In [13]:
z_t = z.t()
z_t

tensor([[3, 4, 2, 4, 4, 1, 2, 2, 2, 4],
        [3, 2, 4, 1, 3, 1, 3, 4, 0, 3]])

In [14]:
id(z.storage()) == id(z_t.storage())

True

## Higher order transpose

In [15]:
s = torch.ones(3, 4, 5)
s_t = s.transpose(0, 2)
s.shape, s_t.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

## Pushing tensor to GPU manually
#### Note that these operations take longer due to the overhead

In [16]:
q_gpu = torch.tensor(list(range(5)), device = "cuda")
s_gpu = s.to(device = "cuda")

## Misc Experimentation

In [17]:
t = torch.tensor(list(range(9)))
b = t.view(3, 3)
print(b)
id(b.storage()) == id(t.storage())

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


True

In [18]:
torch.cos(t.float())

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [19]:
s = t.float()
print(s)
torch.cos_(s) ## In place operation
s

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])


tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])